/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './src/routes/__root'
import { Route as LoginRouteImport } from './src/routes/_authenticated'
import { Route as BoardsIndexRouteImport } from './src/routes/_authenticated/boards'
import { Route as BoardsBoardIdRouteImport } from './src/routes/_authenticated/board.$boardId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/boards/': typeof BoardsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/boards': typeof BoardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/boards/': typeof BoardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/boards/$boardId' | '/boards/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/boards/$boardId' | '/boards'
  id: '__root__' | '/login' | '/boards/$boardId' | '/boards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
  BoardsIndexRoute: typeof BoardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  BoardsIndexRoute: BoardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
